name: Build docker for dev

on:
  push:
    branches:
      - dev
    paths:
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.css'
      - '**/*.scss'
      - 'package.json'
      - 'Dockerfile'
      - '.github/workflows/deploy-dev.yml'

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/pomnesh-frontend-dev
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          username: ${{ secrets.DEV_SERVER_USER }}
          key: ${{ secrets.DEV_SERVER_SSH_KEY }}
          script: |
            echo "Deploying container..."
            docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            docker stop pomnesh-frontend || true
            docker rm pomnesh-frontend || true
          
            docker run -d \
              --name pomnesh-frontend \
              -p 9000:80 \
              ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} 